routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
*/
use App\Product;
use App\Category;
use App\Imagemaster;
use App\Review;
use Illuminate\Support\Facades\Input;
use App\jrz;

// Route for Homepage - displays all products from the shop
Route::get('/', function()
{
	$imagesmaster = Imagemaster::all();
	$categories = Category::all();
	$products = Product::all();
	return View::make('index', array('products'=>$products, 'imagesmaster'=>$imagesmaster, 'categories'=>$categories));
});

// Route that shows an individual product by its ID
Route::get('products/{id}', function($id)
{
	$product = Product::find($id);
	$categories = Category::all();
	$product->views += 1;
	$product->save();
	$product->parseHTML();
	// Get all reviews that are not spam for the product and paginate them
	$reviews = $product->reviews()->with('user')->approved()->notSpam()->orderBy('created_at','desc')->paginate(100);

	return View::make('products.single', array('product'=>$product,'reviews'=>$reviews,'categories'=>$categories));
});

// Route that handles submission of review - rating/comment
Route::post('products/{id}', array('before'=>'csrf', function($id)
{
	$input = array(
		'comment' => Input::get('comment'),
		'rating'  => Input::get('rating')
	);
	// instantiate Rating model
	$review = new Review;

	// Validate that the user's input corresponds to the rules specified in the review model
	$validator = Validator::make( $input, $review->getCreateRules());

	// If input passes validation - store the review in DB, otherwise return to product page with error message 
	if ($validator->passes()) {
		$review->storeReviewForProduct($id, $input['comment'], $input['rating']);
		return Redirect::to('products/'.$id.'#reviews-anchor')->with('review_posted',true);
	}
	
	return Redirect::to('products/'.$id.'#reviews-anchor')->withErrors($validator)->withInput();
}));

Route::group(['middleware' => ['auth','jrz']], function () {
	Route::get('/jrz/product', 'ProductController@create');
	Route::get('/jrz/products', 'ProductController@index');

	Route::get('/jrz/images', 'ImagemasterController@create');
	Route::post('/jrz/images', 'ImagemasterController@store');
	Route::get('/jrz/imagesall', 'ImagemasterController@index');
	Route::post('/jrz/images/delete', 'ImagemasterController@destroy');

	Route::get('/jrz/categories', 'CategoryController@index');
	Route::get('/jrz/category', 'CategoryController@create');
	Route::post('/jrz/category', 'CategoryController@store');
	Route::post('/jrz/category/edit', 'CategoryController@update');
	Route::post('/jrz/categories/delete', 'CategoryController@destroy');

	Route::get('/jrz/subcategories', 'SubcategoryController@index');
	Route::get('/jrz/subcategory', 'SubcategoryController@create');
	Route::post('/jrz/subcategory', 'SubcategoryController@store');
	Route::post('/jrz/subcategory/edit', 'SubcategoryController@update');
	Route::post('/jrz/subcategories/delete', 'SubcategoryController@destroy');
});

Route::group(['middleware' => ['auth']], function () {

	Route::post('/jrz/product', 'ProductController@store');
	Route::post('/jrz/product/edit', 'ProductController@update');
	Route::post('/jrz/products/delete', 'ProductController@destroy');

	/*AJAX*/
	Route::post('/sendMessage', 'MessageController@storeMessageAJAX');
	Route::post('/getMessages', 'MessageController@getMessagesAJAX');

	Route::post('/message', 'MessageController@store');
	Route::post('/message/user', 'MessageController@chat');
	Route::get('/profile', 'UserController@showProfile');
	Route::post('/profile/edit', 'UserController@editProfile');
});

	Route::get('/products/subcategory/{id}', 'ProductController@showBySubcategory');
	Route::get('/user/{username}', 'UserController@show');

Auth::routes();

Route::get('/search', 'SearchController@search');
Route::get('/autocomplete', array('as'=>'autocomplete', 'uses'=>'SearchController@autocomplete'));


Route::get('auth/facebook', [
	'as' 	=> 'auth-facebook',
	'uses'	=> 'SocialAuthController@redirectToProvider'
]);

Route::get('auth/facebook/callback', [
	'as'	=> 'facebook-callback',
	'uses'	=> 'SocialAuthController@handleProviderCallback'
]);

Route::resource('product', 'ProductController');

/* AJAX */

Route::get('subcategories/subcategoriesByCategory/{category_id}',[
	'uses' 	=> 'SubcategoryController@showByCategory',
	'as' 	=> 'subcategory.showByCategory',
]);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
	protected $fillable = ['name', 'pricing', 'category_id', 'user_id', 'subcategory_id', 'short_description', 'long_description', 'icon', 'available', 'published', 'created_at', 'updated_at'];

	public function reviews()
	{
	    return $this->hasMany('App\Review');
	}

	public function images()
	{
	    return $this->hasMany('App\Image');
	}

	public function user()
	{
		return $this->belongsTo('App\User');
	}

	// The way average rating is calculated (and stored) is by getting an average of all ratings, 
	// storing the calculated value in the rating_cache column (so that we don't have to do calculations later)
	// and incrementing the rating_count column by 1

    public function recalculateRating($rating)
    {
    	
    	$reviews = $this->reviews()->notSpam()->approved();
	    $avgRating = $reviews->avg('rating');
		$this->rating_cache = round($avgRating,1);
		$this->rating_count = $reviews->count();
    	$this->save();
    }

    public function parseHTML()
    {
    	$this->long_description= str_replace(">","<br>",$this->long_description);

    	$this->long_description = preg_replace('#\*{2}(.*?)\*{2}#', '<b>$1</b>', $this->long_description);
    }
}

app/Review.php
<?php

namespace App;
use Auth;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    
    // Validation rules for the ratings
    public function getCreateRules()
    {
        return array(
            'comment'=>'required|min:10',
            'rating'=>'integer|between:1,5'
        );
    }

    // Relationships
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function product()
    {
        return $this->belongsTo('Product');
    }

    // Scopes
    public function scopeApproved($query)
    {
       	return $query->where('approved', true);
    }

    public function scopeSpam($query)
    {
       	return $query->where('spam', true);
    }

    public function scopeNotSpam($query)
    {
       	return $query->where('spam', false);
    }

    // Attribute presenters
    public function getTimeagoAttribute()
    {
    	$date = \Carbon\Carbon::createFromTimeStamp(strtotime($this->created_at))->diffForHumans();
    	return $date;
    }

    // this function takes in product ID, comment and the rating and attaches the review to the product by its ID, then the average rating for the product is recalculated
    public function storeReviewForProduct($productID, $comment, $rating)
    {
        $product = Product::find($productID);
        if (Auth::user()) {
            $this->user_id = Auth::user()->id;
        }else{
            $this->user_id = 0;
        }
        $this->comment = $comment;
        if (is_null($rating) || $rating == "") {
            $this->rating = 3;
        }else{
            $this->rating = $rating;
        }
        $product->reviews()->save($this);

        // recalculate ratings for the specified product
        $product->recalculateRating($rating);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use View;
use Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Session;
use App\Image;
use App\Category;
use App\Subcategory;
use App\Product;
use Image as ImageService;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $products = Product::all();
        return View::make('products.index', array('products'=>$products, 'categories'=>$categories));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
            $categories = Category::all();
            return View::make('products.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        $this->validate($request, [
        ]);
        $request->request->add(['user_id' => $user->id]);
        // dd($request->all());
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'pricing' => 'required|numeric',
            'icon' => 'required',
            'available' => 'required|numeric',
            'category_id' => 'required',
            'subcategory_id' => 'required',
            'short_description' => 'required|min:10',
            'long_description' => 'required|min:20',
            'image' => 'required',
            'image.*' => 'image|mimes:jpg,jpeg,png'
        ]);
        // dd($request->all());
        if ($validator->fails()) {
            return Redirect::back()
                        ->withErrors($validator)
                        ->withInput();
        }
        // dd($request->all());
        $product = Product::create($request->all());
        if (Input::hasFile('image')) { 
             // getting all of the post data
            $files = Input::file('image');
            // Making counting of uploaded images
            $file_count = count($files);
            // start count how many uploaded
            $uploadcount = 0;
            foreach($files as $file) {
                // $rules = array('file' => 'required|image|mimes:jpg,png'); //'required|mimes:png,gif'
                // $rules = [];

                // $imageRules = array(
                //     'image' => 'image|max:2000'
                // );
                //$validator = Validator::make($file, $imageRules);
                $destinationPath = 'uploads/';
                // $filename = $file->getClientOriginalName();
                $extension = $file->getClientOriginalExtension(); // getting image extension
                $filename = str_random(10) . rand(11111,99999); // renameing image
                $fullname_image = $destinationPath.$filename.'.'.$extension;
                $upload_success = $file->move($destinationPath, $filename.'.'.$extension);
                // $upload_success = ImageService::make($file)->resize(null, 720, function($constraint){
                //     $constraint->aspectRatio();
                // })->save($destinationPath.$filename.'.'.$extension, 100);
                if(!file_exists($destinationPath."thumb/")){
                    mkdir($destinationPath."thumb/", 0777, true);
                }
                $thumb = ImageService::make($fullname_image)->resize(240, 160)->save($destinationPath. "thumb/" .$filename.'.'.$extension, 90);
                $uploadcount ++;
                $image =  new Image;
                $image->product_id = $product->id;
                $image->path =  $destinationPath;
                $image->imagename = $filename;
                $image->ext = $extension;
                $image->save();
                if($uploadcount == 1){
                    $product->icon = $destinationPath .'thumb/'. $filename.'.'.$extension;
                    $product->save();
                }
                // dd($validator->messages());
            }
            if($uploadcount == $file_count){
                Session::flash('success', 'Success!'); 
                return Redirect::to('/');
            } 
            

        }
        Session::flash('success', 'Success!'); 
        return Redirect::to('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function showBySubcategory($subcategory_id='')
    {
        $products = Product::where('subcategory_id', $subcategory_id)->get();
        $categories = Category::all();
        return View::make('products.subcategory')->with('products', $products)->with('categories', $categories);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $user = Auth::user();
        if($user->name === "admin" && $user->email === "admin@email.com"){
            $this->validate($request, [
            ]);
            $request->request->add(['user_id' => $user->id]);
            // dd($request->all());
            $validator = Validator::make($request->all(), [
                'name' => 'required',
                // 'pricing' => 'required|numeric',
                // 'icon' => 'required',
                // 'available' => 'required|numeric',
                // 'category_id' => 'required',
                // 'subcategory_id' => 'required',
                // 'short_description' => 'required|min:10',
                // 'long_description' => 'required|min:20',
                // 'image' => 'required',
                // 'image.*' => 'image|mimes:jpg,jpeg,png'
            ]);
            // dd($request->all());
            if ($validator->fails()) {
                return Redirect::back()
                            ->withErrors($validator)
                            ->withInput();
            }
            $product = Product::find($request->product_id);
            $product->name = $request->name;
            $product->pricing = $request->pricing;
            $product->available = $request->available;
            $product->short_description = $request->short_description;
            $product->long_description = $request->long_description;
            $product->save();
            return Redirect::back();
        }else{
            return Redirect::to('/');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $user = Auth::user();
        if($user->name === "admin" && $user->email === "admin@email.com"){
            $images = Image::select('');
            $product = Product::find($request->product_id);
            $product->images->each(function($image, $key){
                $image->delete();
            });  
            Product::destroy($request->product_id);   
            return Redirect::back();
        }else{
            return Redirect::to('/');
        }
    }
}

resources/views/products/single.blade.php
@extends('layout')

@section('scripts')
  {{Html::script('js/expanding.js')}}
  {{Html::script('js/starrr.js')}}

  <script type="text/javascript">
    $(function(){

      // initialize the autosize plugin on the review text area
      $('#new-review').autosize({append: "\n"});

      var reviewBox = $('#post-review-box');
      var newReview = $('#new-review');
      var openReviewBtn = $('#open-review-box');
      var closeReviewBtn = $('#close-review-box');
      var ratingsField = $('#ratings-hidden');

      openReviewBtn.click(function(e)
      {
        reviewBox.slideDown(400, function()
          {
            $('#new-review').trigger('autosize.resize');
            newReview.focus();
          });
        openReviewBtn.fadeOut(100);
        closeReviewBtn.show();
      });

      closeReviewBtn.click(function(e)
      {
        e.preventDefault();
        reviewBox.slideUp(300, function()
          {
            newReview.focus();
            openReviewBtn.fadeIn(200);
          });
        closeReviewBtn.hide();
        
      });

      // If there were validation errors we need to open the comment form programmatically 
      @if($errors->first('comment') || $errors->first('rating'))
        openReviewBtn.click();
      @endif

      // Bind the change event for the star rating - store the rating value in a hidden field
      $('.starrr').on('starrr:change', function(e, value){
        ratingsField.val(value);
      });
    });
  </script>
@stop

@section('styles')
  <style type="text/css">

     /* Enhance the look of the textarea expanding animation */
     .animated {
        -webkit-transition: height 0.2s;
        -moz-transition: height 0.2s;
        transition: height 0.2s;
      }

      .stars {
        margin: 20px 0;
        font-size: 24px;
        color: #d17581;
      }
  </style>
@stop

@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h2>{!! Session::get('success') !!} <a href="/profile">Go to my messages</a></h2>
        </div>
    @endif
    <div class="row">

    <!--     <div class="col-md-3">
            <p class="lead">Shop Categories</p>
            <div class="list-group">
              <a href="#" class="list-group-item active">Electronicos</a>
              <a href="#" class="list-group-item">Categoria 1</a>
            </div>
        </div> -->
        <div class="col-md-9">

            <div class="thumbnail">
              <div class="row" style="margin-bottom:30px;">
                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                        @foreach($product->images as $image)
                            @if($loop->iteration == 1)
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            @else
                            <li data-target="#carousel-example-generic" data-slide-to="{{$loop->iteration - 1}}"></li>

                            @endif
                        @endforeach
                        </ol>
                        <div class="carousel-inner">
                        @foreach($product->images as $image)
                            @if($loop->iteration == 1)
                            <div class="item active">
                            @else
                            <div class="item">
                            @endif
                            <img alt="First slide"  src="{{url('/')}}/{{$image->path}}/{{$image->imagename}}.{{$image->ext}}" class="image-carousel">
                          </div>
                        @endforeach
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                          <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                          <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>
              <div class="caption-full">
                  <h4 class="pull-right">${{ number_format($product->pricing, 2)}}</h4>
                  <h4><a href="{{url('products/'.$product->id)}}">{{$product->name}}</a></h4>
                  <p>{{$product->short_description}}</p>
                  <p id="long_description">{{$product->long_description}}</p>
                  <p>Cantidad disponible: {{number_format($product->available, 0)}}</p>
                  <p><a href="/user/{{$product->user->name}}">{{$product->user->name}}</a></p>
                  <button type="button" data-toggle="modal" data-target="#send_message_modal" class="btn btn-success btn-sm">Message {{$product->user->name}}</button>

              </div>
              <div class="ratings">
                  <p class="pull-right">{{$product->rating_count}} {{ \Illuminate\Support\Str::plural('review', $product->rating_count)}}</p>
                  <p>
                    @for ($i=1; $i <= 5 ; $i++)
                      <span class="glyphicon glyphicon-star{{ ($i <= $product->rating_cache) ? '' : '-empty'}}"></span>
                    @endfor
                    {{ number_format($product->rating_cache, 1)}} stars
                  </p>
              </div>
            </div>
            <div class="well" id="reviews-anchor">
              <div class="row">
                <div class="col-md-12">
                  @if(Session::get('errors'))
                    <div class="alert alert-danger">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                       <h5>There were errors while submitting this review:</h5>
                       @foreach($errors->all('<li>:message</li>') as $message)
                          {{$message}}
                       @endforeach
                    </div>
                  @endif
                  @if(Session::has('review_posted'))
                    <div class="alert alert-success">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <h5>Your review has been posted!</h5>
                    </div>
                  @endif
                  @if(Session::has('review_removed'))
                    <div class="alert alert-success">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <h5>Your review has been removed!</h5>
                    </div>
                  @endif
                </div>
              </div>
              <div class="text-right">
                <a href="#reviews-anchor" id="open-review-box" class="btn btn-success btn-green">Leave a Review</a>
              </div>
              <div class="row" id="post-review-box" style="display:none;">
                <div class="col-md-12">
                  {{Form::open()}}
                  {{Form::hidden('rating', null, array('id'=>'ratings-hidden'))}}
                  {{Form::textarea('comment', null, array('rows'=>'5','id'=>'new-review','class'=>'form-control animated','placeholder'=>'Enter your review here...'))}}
                  <div class="text-right">
                    <div class="stars starrr" data-rating="{{Illuminate\Support\Facades\Input::old('rating',0)}}"></div>
                    <a href="#" class="btn btn-danger" id="close-review-box" style="display:none; margin-right:10px;"> <span class="glyphicon glyphicon-remove"></span>Cancel</a>
                    <button class="btn btn-success" type="submit">Save</button>
                  </div>
                {{Form::close()}}
                </div>
              </div>

              @foreach($reviews as $review)
              <hr>
                <div class="row">
                  <div class="col-md-12">
                    @for ($i=1; $i <= 5 ; $i++)
                      <span class="glyphicon glyphicon-star{{ ($i <= $review->rating) ? '' : '-empty'}}"></span>
                    @endfor
                    
                    {!! $review->user ? '<a href="/user/'.$review->user->name.'">'. $review->user->name.'</a>' : 'Anonymous'!!} <span class="pull-right">{{$review->timeago}}</span> 
                    
                    <p>{{{$review->comment}}}</p>
                  </div>
                </div>
              @endforeach
              {{ $reviews->links() }}
            </div>
        </div>

    </div>

    <div class="modal fade" id="send_message_modal" tabindex="-1" role="dialog" aria-labelledby="send" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                    <h4 class="modal-title custom_align" id="Heading">Send Message</h4>
                </div>
                {!! Form::open(array('url'=>'/message','method'=>'POST', 'files'=>true)) !!}
                <div class="modal-body">
                    <div class="form-group {{ $errors->has('message') ? ' has-error' : '' }} ">
                        <label for="message">Message</label>
                        <textarea class="form-control" title="message" id="message" name="message" placeholder="Message" rows="5" >{{ Request::old('message') ? : '' }}</textarea>
                        @if($errors->has('message'))
                            <span class="help-block">{{ $errors->first('message') }}</span>
                        @endif 
                    </div>
                </div>
                    {{ csrf_field() }}
                    <input type="hidden" id="user_id" name="user_id" value="{{$product->user->id}}" ></input>

                <div class="modal-footer ">
                    <button type="submit" class="btn btn-success" >Send</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/products/subcategory.blade.php
@extends('layout')

@section('content')
    @if(Session::has('success'))
    <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h2>{!! Session::get('success') !!}</h2>
        </div>
    @endif
    <div class="row">
        <div class="col-md-3">

            <ul class="nav nav-pills nav-stacked" id="stacked-menu">
            @foreach($categories as $category)
                <li>
                    <a class="nav-container" data-toggle="collapse" data-parent="#stacked-menu" href="#p{{$loop->iteration}}">{{$category->name}}<span class="caret arrow"></span></a>    
                    @if($loop->iteration == 1)
                        <ul class="nav nav-pills nav-stacked collapse in" id="p{{$loop->iteration}}">
                    @else
                        <ul class="nav nav-pills nav-stacked collapse" id="p{{$loop->iteration}}">
                    @endif
                    @foreach($category->subcategories as $subcategory)
                        <li><a href="/products/subcategory/{{$subcategory->id}}">{{$subcategory->name}}</a></li>
                    @endforeach
                        </ul>
                </li>
            @endforeach
            </ul>


        </div>
        {{-- <div class="col-md-1"></div> --}}
        <div class="col-md-9">
            <div class="row">
            @foreach($products as $product)
                <div class="col-sm-4 col-lg-4 col-md-4">
                  <div class="thumbnail">
                    <img src="/{{$product->icon}}" alt="" style="max-height: 250px; max-width: 100%;">
                    <div class="caption">
                        <div class="row">
                            <div class="col-sm-9">
                                <h4 class="scrollEffectText" ><span class="overflowContent h4" style="margin-left: 0px;"><a href="{{url('products/'.$product->id)}}" style="text-overflow: ellipsis; text-decoration: none !important;">{{$product->name}}</a></span></h4>
                            </div>
                            <div class="col-sm-3" style="background-color: white;">
                                <h4 >${{ number_format($product->pricing, 2)}}</h4>
                            </div>
                        </div>
                        <p>{{$product->short_description}}</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">{{$product->rating_count}} {{  \Illuminate\Support\Str::plural('review', $product->rating_count)}}</p>
                        <p>
                            @for ($i=1; $i <= 5 ; $i++)
                                <span class="glyphicon glyphicon-star{{ ($i <= $product->rating_cache) ? '' : '-empty'}}"></span>
                            @endfor
                        </p>
                    </div>
                  </div>
                </div>
            @endforeach
            </div>
        </div>
        {{-- <div class="col-md-1"></div> --}}
    </div>
@stop